quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:appuser}
quarkus.datasource.password=${POSTGRES_PASSWORD:apppassword}
quarkus.datasource.reactive.url=${POSTGRES_URL:postgresql://4.168.235.59:5432/${POSTGRES_DB:appdb}}

# Hibernate configuration
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true
